<?php

namespace App\Services\Scm;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Carbon\Carbon;
use Exception;

class ScmCarryingOutService
{
    protected $ledgerService;

    public function __construct(ScmLedgerService $ledgerService)
    {
        $this->ledgerService = $ledgerService;
    }

    /**
     * Process Carrying Out (Outbound)
     * 
     * @param int $whSeq Warehouse Sequence
     * @param int $traderSeq Trader Sequence
     * @param array $items Array of ['goods_seq', 'option_seq', 'ea', 'supply_price']
     * @return int Created Carrying Out Sequence (cro_seq)
     */
    public function processCarryingOut(int $whSeq, int $traderSeq, array $items)
    {
        return DB::transaction(function () use ($whSeq, $traderSeq, $items) {
            // 1. Generate Code
            $croSeq = DB::table('fm_scm_carryingout')->max('cro_seq') + 1;
            $croCode = 'CRO' . date('YmdHis') . $croSeq;

            // 2. Create Header
            $croSeq = DB::table('fm_scm_carryingout')->insertGetId([
                'cro_code' => $croCode,
                'cro_status' => '1', // Complete
                'cro_type' => 'E', // Etc/Manual
                'trader_seq' => $traderSeq,
                'wh_seq' => $whSeq,
                'regist_date' => Carbon::now(),
                'complete_date' => Carbon::now(),
                'chg_log' => 'Auto-generated by SCM Migration',
            ]);

            $ledgerTargets = [];
            $totalEa = 0;
            $totalPrice = 0;

            foreach ($items as $item) {
                // Fetch Goods Info for snapshot
                $goods = DB::table('fm_goods')
                    ->where('goods_seq', $item['goods_seq'])
                    ->first();
                
                $option = DB::table('fm_goods_option')
                    ->where('goods_seq', $item['goods_seq'])
                    ->where('option_seq', $item['option_seq'])
                    ->first();

                if (!$goods || !$option) {
                    throw new Exception("Goods or Option not found: {$item['goods_seq']}, {$item['option_seq']}");
                }

                // 3. Create Details
                // Note: Legacy stores 'ea' as positive in this table, but logic implies out.
                // We will follow legacy pattern: Store positive EA, but decrement stock.
                DB::table('fm_scm_carryingout_goods')->insert([
                    'cro_seq' => $croSeq,
                    'goods_seq' => $item['goods_seq'],
                    'goods_code' => $goods->goods_code ?? '',
                    'goods_name' => $goods->goods_name,
                    'option_type' => $item['option_type'] ?? 'option', // Default to option
                    'option_seq' => $item['option_seq'],
                    'option_name' => $option->option1 . ($option->option2 ? ' ' . $option->option2 : ''),
                    'ea' => $item['ea'],
                    'supply_price' => $item['supply_price'] ?? 0,
                    'krw_supply_price' => $item['supply_price'] ?? 0,
                ]);

                // 4. Update Stock (Decrement)
                DB::table('fm_goods_supply')
                    ->where('goods_seq', $item['goods_seq'])
                    ->where('option_seq', $item['option_seq'])
                    ->decrement('stock', $item['ea']);
                
                 DB::table('fm_goods_supply')
                    ->where('goods_seq', $item['goods_seq'])
                    ->where('option_seq', $item['option_seq'])
                    ->decrement('total_stock', $item['ea']);

                // Prepare for ledger
                $ledgerTargets[] = [
                    'goods_seq' => $item['goods_seq'],
                    'option_seq' => $item['option_seq'],
                    'option_type' => $item['option_type'] ?? 'option'
                ];

                $totalEa += $item['ea'];
                $totalPrice += ($item['supply_price'] ?? 0) * $item['ea'];
            }

            // Update Header Totals
            DB::table('fm_scm_carryingout')
                ->where('cro_seq', $croSeq)
                ->update([
                    'total_ea' => $totalEa,
                    'krw_total_price' => $totalPrice
                ]);

            // 5. Update Stock Ledger
            if (!empty($ledgerTargets)) {
                $this->ledgerService->updateDailyLedger($whSeq, $ledgerTargets);
            }

            return $croSeq;
        });
    }
}
